name: fursal_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^6.1.0
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  google_fonts: ^6.3.0
  flutter_svg: ^2.1.0
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  android_12:
    image: assets/splash.png
    color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - .env
